INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'f1GbGBCd', '10', 'INTERNATIONAL FRIENDLY');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'Y35Jer59', '41264', 'FRANCE DOMINO''S LIGUE 2');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'lrMHUHDc', '8401', 'Poland Ekstraklasa');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'dG2SqPrf', '41314', 'BELGIUM FIRST DIVISION A');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'lfZXonNq', '19097', 'Australia Victorian Premier League');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'EPQbW9EF', '52091', 'Austria 2nd Liga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', '2DSCa5fE', '86', 'ENGLISH CHAMPIONSHIP');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'YacqHHdS', '169', 'Russia Premier League');
