INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'f1GbGBCd', '10', 'INTERNATIONAL FRIENDLY');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'Y35Jer59', '41264', 'FRANCE DOMINO''S LIGUE 2');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'lrMHUHDc', '8401', 'Poland Ekstraklasa');
