INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'f1GbGBCd', '10', 'INTERNATIONAL FRIENDLY');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('SBOBET', 'lvUBR5F8', '48082', 'WORLD CUP 2018 (in Russia)');
