/*  INTERNATIONAL FRIENDLY - 10 - f1GbGBCd   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES('SBOBET', 'naHiWdnt', '', 'Austria');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES('SBOBET', 'hrgrswHh', '', 'Russia');
