INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'f1GbGBCd', '2117', 'International - Friendlies');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'lvUBR5F8', '2686', 'FIFA - World Cup');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'lrMHUHDc', '2374', 'Poland - Ekstraklasa');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'Y35Jer59', '2037', 'France - Ligue 2');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'dG2SqPrf', '1817', 'Belgium - First Division A');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'dMwNgPSC', '1818', 'Belgium - First Division B');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'lfZXonNq', '1769', 'Australia NPL - Victoria');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'EPQbW9EF', '1773', 'Austria - Erste Liga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', '2DSCa5fE', '1977', 'England - Championship');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'YacqHHdS', '2406', 'Russia - Premier League');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'EBPEFrRQ', '10914', 'Australia - Brisbane Capital League 1');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'O6W7GIaF', '1913', 'Denmark - Superliga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'lpTTNvTq', '2024', 'Finland - Veikkausliiga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'tKH71vSe', '1843', 'Germany - Bundesliga 2');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'fNLB0bs2', '1844', 'Germany - Bundesliga 3');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'hleea1wH', '1891', 'Czech Republic - Czech Liga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'Qo6off6p', '6633', 'Poland - 1st Liga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'jVMQJOHF', '201159', 'Switzerland - Liga 1');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'nqMxclRN', '1880', 'Croatia - 1. HNL');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'r9Y9rlDt', '9320', 'Bulgaria - A PFG');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'bBIP6pm3', '2476', 'Sweden - Superettan');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'xbpjAGxq', '9885', 'Egypt - Premier League');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', '2HzmcynI', '2118', 'Iran - Pro League');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'KrrdAMyI', '2366', 'Peru - Primera Division');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'vXr8fotG', '2159', 'Japan - J2 League');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', '0IDCJLlH', '2185', 'Korea Republic - K League Classic');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'GOvB22xg', '2333', 'Norway - Eliteserien');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'nXxWpLmT', '1728', 'Sweden - Allsvenskan');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'rJSMG3H0', '1957', 'England - League 1');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', '0MwU4NW6', '1958', 'England - League 2');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'dYlOSQOD', '1980', 'England - Premier League');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'Or1bBrWD', '1928', 'Netherlands - Eredivisie');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'KIShoMk3', '2036', 'France - Ligue 1');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'xfzNMq1a', '2188', 'Korea - National League');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'UmMRoGzp', '2386', 'Portugal - Primeira Liga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'vZiPmPJi', '10317', 'Spain - Segunda B');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'Opdcd08Q', '2592', 'Turkey - Super League');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', '6Nl8nagD', '1929', 'Netherlands - Eerste Divisie');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'pv9Nf2KF', '2027', 'France - National');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'QVmLl54o', '2196', 'Spain - La Liga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('PINNACLE', 'jizXHcsM', '35174', 'Russia - FNL');




























