/*  INTERNATIONAL FRIENDLY - 2117 - f1GbGBCd   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES('PINNACLE', '6LHwBDGU', '', 'Czech Republic (n)');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES('PINNACLE', 'EBE2Xb3l', '', 'Nigeria');
