INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'Y35Jer59', '', 'France.Ligue 2');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'lrMHUHDc', '', 'Poland.Ekstraklasa');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'Y35Jer59', '', 'Belgium.1st Division A');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'dMwNgPSC', '', 'Belgium.1st Division B');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'lfZXonNq', '', 'Australia.National Premier League.Victoria');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'EPQbW9EF', '', 'Austria.2 Liga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', '2DSCa5fE', '', 'England.Championship');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'YacqHHdS', '', 'Russia.Premier League');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'tKH71vSe', '', 'Germany.Bundesliga 2');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'O6W7GIaF', '', 'Denmark.Superliga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'lpTTNvTq', '', 'Finland.Veikkausliiga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'fNLB0bs2', '', 'Germany.3rd Liga');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'hleea1wH', '', 'Czech Republic.1st League');
INSERT INTO PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME)  VALUES('MARATHON', 'Qo6off6p', '', 'Poland.I Liga');












