scheduling:
  enabled: true
server:
    port: 8002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
spring:
    datasource:
        hikari:
                    minimum-idle: 1
                    maximum-pool-size: 5
                    pool-name: forks-pool
        url: jdbc:h2:file:./engine;AUTO_SERVER=TRUE;FILE_LOCK=SOCKET
        driver-class-name: org.h2.Driver
        user: sa
        password:
        type: com.zaxxer.hikari.HikariDataSource
    jpa:
        properties:
              hibernate:
                    dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: validate
            use-new-id-generator-mappings: true
        show-sql: true
feign:
  hystrix:
    enabled: true