CREATE TABLE PUBLIC.BOOKMAKER_LEAGUE (
	BOOKMAKER_TYPE VARCHAR(255) NOT NULL,
	ITEM_FLASHSCORE_ID VARCHAR(255) NOT NULL,
	BOOKMAKER_ID VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	CONSTRAINT CONSTRAINT_8 PRIMARY KEY (BOOKMAKER_TYPE,ITEM_FLASHSCORE_ID)
) ;
/*CREATE UNIQUE INDEX PRIMARY_KEY_8 ON PUBLIC.BOOKMAKER_LEAGUE (BOOKMAKER_TYPE,ITEM_FLASHSCORE_ID) ;*/


CREATE TABLE PUBLIC.BOOKMAKER_TEAM (
	BOOKMAKER_TYPE VARCHAR(255) NOT NULL,
	ITEM_FLASHSCORE_ID VARCHAR(255) NOT NULL,
	BOOKMAKER_ID VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	CONSTRAINT CONSTRAINT_3 PRIMARY KEY (BOOKMAKER_TYPE,ITEM_FLASHSCORE_ID)
) ;

CREATE TABLE PUBLIC.TEAM (
	FLASHSCORE_ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	SPORT_TYPE VARCHAR(255) NOT NULL,
	CONSTRAINT CONSTRAINT_2 PRIMARY KEY (FLASHSCORE_ID)
);
/*CREATE UNIQUE INDEX PRIMARY_KEY_2 ON PUBLIC.TEAM (FLASHSCORE_ID) ;*/



CREATE TABLE PUBLIC.MATCH (
	FLASHSCORE_ID VARCHAR(255) NOT NULL,
	"DATE" TIMESTAMP NOT NULL,
	FLASHSCORE_LEAGUE_ID VARCHAR(255) NOT NULL,
	MATCH_STATUS VARCHAR(255) NOT NULL,
	SPORT_TYPE VARCHAR(255) NOT NULL,
	AWAY_TEAM_FLASHSCORE_ID VARCHAR(255) NOT NULL,
	HOME_TEAM_FLASHSCORE_ID VARCHAR(255) NOT NULL,
	CONSTRAINT CONSTRAINT_4 PRIMARY KEY (FLASHSCORE_ID),
	CONSTRAINT FK4F7J7B92FPKHSLJ3CLA9OM4BF FOREIGN KEY (HOME_TEAM_FLASHSCORE_ID) REFERENCES PUBLIC.TEAM(FLASHSCORE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FKFKCP12AKI4HCKPTXSKQ92ECBJ FOREIGN KEY (AWAY_TEAM_FLASHSCORE_ID) REFERENCES PUBLIC.TEAM(FLASHSCORE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
) ;
/*CREATE INDEX FK4F7J7B92FPKHSLJ3CLA9OM4BF_INDEX_4 ON PUBLIC."MATCH" (HOME_TEAM_FLASHSCORE_ID) ;
CREATE INDEX FKFKCP12AKI4HCKPTXSKQ92ECBJ_INDEX_4 ON PUBLIC."MATCH" (GUEST_TEAM_FLASHSCORE_ID) ;
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC."MATCH" (FLASHSCORE_ID) ;*/







