/*  INTERNATIONAL FRIENDLY - 10 - f1GbGBCd   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''naHiWdnt'', '''', ''Austria'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hrgrswHh'', '''', ''Russia'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6LHwBDGU'', '''', ''Czech Republic (n)'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EBE2Xb3l'', '''', ''Nigeria'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WC2jLpW4'', '''', ''Latvia'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UTJj1saj'', '''', ''Azerbaijan'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MTVhw6Go'', '''', ''Hungary'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''xSrf6qMM'', '''', ''Australia'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''I9l9aqLq'', '''', ''Brazil'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''biSY8ox4'', '''', ''Saudi Arabia'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''f9OppQjp'', '''', ''Argentina'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6TsAIrGN'', '''', ''Iceland'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''QkGeVG1n'', '''', ''France'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Uend67D3'', '''', ''Peru'');

/*  FRANCE LIGUE 2 - 41264 - Y35Jer59   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MTLr36WA'', '''', ''Auxerre'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''QZuxDxup'', '''', ''GFC Ajaccio'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CWwUNPzA'', '''', ''Beziers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2aeoANM8'', '''', ''AC Ajaccio'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CIEe04GT'', '''', ''Le Havre'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UgPj1p1N'', '''', ''Grenoble'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''4v0yqlWc'', '''', ''Metz'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''AqswAEFD'', '''', ''Orleans'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SW30dLbl'', '''', ''Niort'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IRuMRua1'', '''', ''Clermont'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''0OEHEprs'', '''', ''Paris FC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dnIrsS0A'', '''', ''Nancy'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jPojkLXK'', '''', ''Sochaux'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''O8dsB372'', '''', ''Valenciennes'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fsfAHubD'', '''', ''Troyes'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Cr4VGaUl'', '''', ''Brest'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jgNAYRGi'', '''', ''Lorient'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jZ2ZFJqe'', '''', ''Chateauroux'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2kM6ufaS'', '''', ''Red Star Saint Ouen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IBmris38'', '''', ''Lens'');

/*  Poland Ekstraklasa - 8401 - lrMHUHDc   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''QoZYVU3E'', '''', ''Plock'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pp78XcbA'', '''', ''Korona Kielce'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''043sUkrq'', '''', ''Zaglebie Sosnowiec'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Um9YwPQ0'', '''', ''Pogon Szczecin'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''E1Oxemse'', '''', ''Slask Wroclaw'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ve2oT9ck'', '''', ''Piast Gliwice'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KvXSf2A6'', '''', ''Cracovia Krakow'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''feEez0Ei'', '''', ''Arka Gdynia'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''GGLmkiK8'', '''', ''Lechia Gdansk'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''rob20Q2Q'', '''', ''Wisla Krakow'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2LH3Ywq4'', '''', ''Gornik Zabrze'');

/*  ENGLISH CHAMPIONSHIP - 86 - 2DSCa5fE   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SWk4muv7'', '''', ''Birmingham City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Qo6off6p'', '''', ''Norwich City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''xYe7DwID'', '''', ''Brentford'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KMfM7P4b'', '''', ''Rotherham United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MahqU27I'', '''', ''Bristol City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UsushcZr'', '''', ''Nottingham Forest'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''thqhB2MB'', '''', ''Ipswich Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6Nl8nagD'', '''', ''Blackburn Rovers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6uz2cJBL'', '''', ''Millwall'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6F0lvLNC'', '''', ''Middlesbrough'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''x8IDVcbi'', '''', ''Preston North End'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lrMHUHDc'', '''', ''Queens Park Rangers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CCBWpzjj'', '''', ''W.B.A'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Or1bBrWD'', '''', ''Bolton Wanderers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MgHlK2Na'', '''', ''Wigan Athletic'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''llcCvIcG'', '''', ''Sheffield Wednesday'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MeKPSerA'', '''', ''Sheffield United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''K6xezbY7'', '''', ''Swansea City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''S66R0t75'', '''', ''Hull City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''W00wmLO0'', '''', ''Aston Villa'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tUxUbLR2'', '''', ''Leeds United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Iug0YO0Q'', '''', ''Derby County'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EmlVDpVP'', '''', ''Reading'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hSUajdSS'', '''', ''Stoke City'');


/*  Korea K-League 1 - 49027 - 0IDCJLlH   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SrMQkOnI'', '''', ''Daegu FC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''prJ1QuXA'', '''', ''Incheon United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vFZJewv4'', '''', ''Jeju United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KIIIipI5'', '''', ''Pohang Steelers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''x0hNfcgA'', '''', ''Jeonbuk Hyundai Motors'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''A144gewT'', '''', ''Gangwon FC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''djpFdJOc'', '''', ''Gyeongnam FC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EuIMj4XB'', '''', ''Jeonnam Dragons'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''v5I5PanH'', '''', ''Suwon Samsung Bluewings'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8tzeYeHp'', '''', ''FC Seoul'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EVEwgyOM'', '''', ''Ulsan Hyundai'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IaoBca9i'', '''', ''Sangju Sangmu FC'');


/*  ENGLISH PREMIER LEAGUE - 3 - dYlOSQOD   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''p6ahwuwJ'', '''', ''Newcastle United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UDg08Ohm'', '''', ''Tottenham Hotspur'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''OtpNdwrc'', '''', ''Bournemouth AFC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hO8wh6aP'', '''', ''Cardiff City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''69ZiU2Om'', '''', ''Fulham'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''AovF1Mia'', '''', ''Crystal Palace'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''xxxpBZl2'', '''', ''Huddersfield Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''4fGZN2oK'', '''', ''Chelsea'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UmMRoGzp'', '''', ''Watford'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2XrRecc3'', '''', ''Brighton & Hove Albion'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''j3Azpf5d'', '''', ''Wolverhampton Wanderers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KluSTr9s'', '''', ''Everton'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WdKOwxDM'', '''', ''Southampton'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KrrdAMyI'', '''', ''Leicester City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Cxq57r8g'', '''', ''West Ham United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hA1Zm19f'', '''', ''Arsenal'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lId4TMwf'', '''', ''Liverpool'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Wtn9Stg0'', '''', ''Manchester City'');


/*  HOLLAND EREDIVISIE - 20 - Or1bBrWD   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8UOvIwnb'', '''', ''Ajax'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''bB3JbZpA'', '''', ''Heracles Almelo'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6u3qag0G'', '''', ''Willem II'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UNA6IKFC'', '''', ''VVV-Venlo'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''nNlLsRUr'', '''', ''Excelsior SBV'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YH8HX5iP'', '''', ''Fortuna Sittard'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''M9UEHJWi'', '''', ''PSV Eindhoven'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''p6QXMgOj'', '''', ''FC Utrecht'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lAgLCkT3'', '''', ''ADO Den Haag'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Stafar0g'', '''', ''FC Emmen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''naL1J006'', '''', ''De Graafschap'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MBUGcjb9'', '''', ''Groningen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''nLNrHc14'', '''', ''NAC Breda'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''r1L5w2EB'', '''', ''PEC Zwolle'');



/*  GERMANY BUNDESLIGA 2 - 35 - tKH71vSe   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WG9pOTse'', '''', ''Koln'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pzHW4oaE'', '''', ''Union Berlin'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8Y2m6ADe'', '''', ''VfL Bochum'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UZxEj1R4'', '''', ''SV Sandhausen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''S0hPB9rA'', '''', ''SV Darmstadt 98'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2s7huW4R'', '''', ''MSV Duisburg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vsXIDreP'', '''', ''Erzgebirge Aue'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CCQGbik8'', '''', ''Greuther Furth'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''G2Op923t'', '''', ''SC Paderborn 07'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YFuz2RLm'', '''', ''Magdeburg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ne5QkLtB'', '''', ''Ingolstadt 04'');



/*  NORWAY ELITESERIEN - 44386 - GOvB22xg   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''l8zGY8hT'', '''', ''Haugesund'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ph9NNA8A'', '''', ''Valerenga'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CbXNfZvn'', '''', ''Stabaek'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IXyr4UxA'', '''', ''Sandefjord'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''xYWBZlwN'', '''', ''Lillestrom'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UPrP2SMS'', '''', ''Sarpsborg 08'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IDDWgzKt'', '''', ''Kristiansund'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''25HpQh9o'', '''', ''Tromso'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''S0WZMUNG'', '''', ''Bodo Glimt'');


/*  SWEDEN ALLSVENSKAN - 25 - nXxWpLmT   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tpjDEBbi'', '''', ''IFK Norrkoping'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SQsg3nME'', '''', ''Hammarby'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KYqn82b7'', '''', ''Trelleborgs FF'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fmfHDVDc'', '''', ''GIF Sundsvall'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UovQtopk'', '''', ''IFK Goteborg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dvUkoqAQ'', '''', ''Ostersunds FK'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''xAfs9rq1'', '''', ''Orebro'');


/*  DENMARK SUPER LEAGUE - 8322 - O6W7GIaF   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pbQ9wvan'', '''', ''Esbjerg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''42ectuVa'', '''', ''Sonderjyske'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WIOwwITb'', '''', ''Horsens'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''U1YrLdqI'', '''', ''Aalborg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zuD4T1wG'', '''', ''Hobro'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''OOXnKGbO'', '''', ''AGF Aarhus'');


/*  SWEDEN SUPERETTAN - 185 - bBIP6pm3   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pAq4eRQ9'', '''', ''Jonkopings Sodra'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''djzjJdOb'', '''', ''IFK Varnamo'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zNSwBuue'', '''', ''Degerfors'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MHuLo5uE'', '''', ''Norrby IF'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jkdD94El'', '''', ''Gefle'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Ye5hqs2o'', '''', ''IK Brage'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KQEAENtF'', '''', ''Osters'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''GC4LebG3'', '''', ''IK Frej'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CGT7Kq4j'', '''', ''Orgryte'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zio11QjR'', '''', ''Helsingborgs'');


/*  Russia Premier League - 169 - YacqHHdS   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''t482C620'', '''', ''Rubin Kazan'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vsXou9m7'', '''', ''Zenit St. Petersburg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''AFWA2jAQ'', '''', ''Dynamo Moscow'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fPxiAl6T'', '''', ''FC Ufa'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ATWL5eS9'', '''', ''Arsenal Tula'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''GbznhOLi'', '''', ''Rostov FK'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tGfC1KkT'', '''', ''Ural Sverdlovsk Oblast'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''bJGqkoet'', '''', ''Akhmat Grozny'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''l0r24CuE'', '''', ''CSKA Moscow'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IXVkvT2D'', '''', ''Spartak Moscow'');



/*  Germany 3rd League - 4177 - fNLB0bs2   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zedZaSL7'', '''', ''Preussen Munster'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hjNlCFPB'', '''', ''Sportfreunde Lotte'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''E5Fv8i93'', '''', ''KFC Uerdingen 05'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''OQZ251DE'', '''', ''SG Sonnenhof Grossaspach'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Oh2C15j0'', '''', ''VfR Aalen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''byXHwsJa'', '''', ''TSV 1860 Munchen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6g44VD52'', '''', ''Energie Cottbus'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''rXqBh2xP'', '''', ''SV Meppen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KIHmtCkL'', '''', ''Hansa Rostock'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''nVM1YUFj'', '''', ''Wurzburger Kickers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''naWckLmC'', '''', ''Kaiserslautern'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EB3q7jbk'', '''', ''Karlsruher SC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''88Xgj1Y5'', '''', ''VfL Osnabruck'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ObxFt3lm'', '''', ''SV Wehen Wiesbaden'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UJfVludH'', '''', ''Unterhaching'');



/*  SPAIN LA LIGA  - 6 - QVmLl54o   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8pvUZFhf'', '''', ''Celta Vigo'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''QFfPdh1J'', '''', ''RCD Espanyol'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lUatW5jE'', '''', ''Villarreal'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jNvak2f3'', '''', ''Real Sociedad'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SKbpVP5K'', '''', ''Barcelona'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hxt57t2q'', '''', ''Alaves'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CQeaytrD'', '''', ''Valencia'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jaarqpLQ'', '''', ''Atletico Madrid'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IP5zl0cJ'', '''', ''Athletic Bilbao'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Mi0rXQg7'', '''', ''Leganes'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dboeiWOt'', '''', ''Getafe'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''OEsEpExD'', '''', ''Eibar'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vJbTeCGP'', '''', ''Real Betis'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8bcjFy6O'', '''', ''Rayo Vallecano'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zkpajjvm'', '''', ''Real Valladolid'');

/*  ENGLISH LEAGUE ONE  - 25353 - rJSMG3H0   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6ZvdGuYf'', '''', ''Accrington Stanley'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fXf5mQ7t'', '''', ''Charlton Athletic'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UNGEKMx6'', '''', ''Barnsley'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''4KREuF43'', '''', ''AFC Wimbledon'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''nwCtJaJT'', '''', ''Burton Albion'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hlzYDy5q'', '''', ''Doncaster Rovers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''GOvB22xg'', '''', ''Coventry City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WpGM6ELj'', '''', ''Plymouth Argyle'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tCZ3D68d'', '''', ''Fleetwood Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''bm2Vlsfl'', '''', ''Rochdale'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tWeI85kh'', '''', ''Peterborough United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SlybbadF'', '''', ''Luton Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zckREQFJ'', '''', ''Portsmouth'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vgOBT43c'', '''', ''Oxford United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EqfQ6qK4'', '''', ''Shrewsbury Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8EFIJthC'', '''', ''Blackpool'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tGwiyvJ1'', '''', ''Southend United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''bsc3EJ27'', '''', ''Bradford City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YgrfcLuL'', '''', ''Walsall'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WvZyDeKk'', '''', ''Gillingham'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hl2V5JIl'', '''', ''Wycombe Wanderers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''GILi6JC9'', '''', ''Bristol Rovers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WSzc94ws'', '''', ''Sunderland'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''r5LLTyT3'', '''', ''Scunthorpe United'');


/*  ENGLISH LEAGUE TWO  - 25354 - 0MwU4NW6   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''bVpINVLD'', '''', ''Bury'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''v7ZNnsJG'', '''', ''Forest Green Rovers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jizXHcsM'', '''', ''Cheltenham Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dUzTIwSF'', '''', ''Carlisle United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YacqHHdS'', '''', ''Crewe Alexandra'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''f9KDxtkU'', '''', ''Milton Keynes Dons'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ve14a3l4'', '''', ''Exeter City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ChwgcrNJ'', '''', ''Newport County'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''t6G9wMZN'', '''', ''Mansfield Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''xYu73rNn'', '''', ''Colchester United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''l4P6dwRR'', '''', ''Northampton Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lnb8EJRp'', '''', ''Cambridge United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''O4voiHlk'', '''', ''Oldham Athletic'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WYFXQ1KH'', '''', ''Macclesfield Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''U3lM3y4e'', '''', ''Port Vale'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''QVmLl54o'', '''', ''Crawley Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ANwyQM2M'', '''', ''Stevenage FC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zmKRcPKu'', '''', ''Morecambe'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''xSloasB8'', '''', ''Swindon Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jVhkb1QE'', '''', ''Tranmere Rovers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hrHTRs5B'', '''', ''Lincoln City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EwJVdqzn'', '''', ''Notts County'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''OEaiS3za'', '''', ''Grimsby Town'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CpsbdueR'', '''', ''Yeovil Town'');

/*  Russia Football National League  - 36096 - jizXHcsM   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WtajPPxR'', '''', ''Chertanovo Moscow'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ALZkiryb'', '''', ''SKA-Khabarovsk'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lvaMZens'', '''', ''FC Tambov'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EHfCCiZl'', '''', ''Mordovia Saransk'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KK7VWueJ'', '''', ''Fakel Voronezh'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pYIyCnmf'', '''', ''FC Khimki'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Wh57DXJr'', '''', ''Avangard Kursk'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2cJYOpxn'', '''', ''Baltika Kaliningrad'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fkpjN4Sk'', '''', ''PFC Sochi'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IFM1GxUm'', '''', ''Nizhny Novgorod FC'');

/*  Scotland League 1  - 26376 - l4P6dwRR   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''S6Xv3lj1'', '''', ''Dumbarton'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''prrz4Uze'', '''', ''Arbroath'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''QmryvWCK'', '''', ''Forfar Athletic'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vudJXTkl'', '''', ''Stranraer'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vinuwjSQ'', '''', ''Montrose'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''OORsaEb2'', '''', ''Brechin City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YJUiAWcR'', '''', ''Raith Rovers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Y5sGF857'', '''', ''East Fife'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dWY6Y9zr'', '''', ''Stenhousemuir'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KWzLBhEq'', '''', ''Airdrieonians'');

/*  PORTUGAL LIGA NOS  - 35741 - UmMRoGzp   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pQYVZyD2'', '''', ''Vitoria Guimaraes'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''t4p0iC41'', '''', ''Feirense'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''noguvetP'', '''', ''Maritimo'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vsToxqA5'', '''', ''GD Chaves'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6ecm9Xlr'', '''', ''Portimonense'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YmQyLBJf'', '''', ''Santa Clara'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zBkyuyRI'', '''', ''Benfica'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tljXuHBC'', '''', ''Sporting Lisbon'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''S2NmScGp'', '''', ''Porto'');


/*  JAPAN J2 LEAGUE  - 33773 - vXr8fotG   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vDpqgnYn'', '''', ''Fagiano Okayama'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IcwgwCCt'', '''', ''Tokushima Vortis'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zNLhJb1S'', '''', ''JEF United Ichihara Chiba'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ppNYGTQb'', '''', ''Tokyo Verdy'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''S6HnxZqN'', '''', ''Kamatamare Sanuki'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KY7LrA6d'', '''', ''Zweigen Kanazawa'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fZS33RAH'', '''', ''Kyoto Sanga'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''4IyNxjsg'', '''', ''Ventforet Kofu'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''0lMXpXdr'', '''', ''Matsumoto Yamaga'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''OlLWoSeO'', '''', ''Yokohama FC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2uKzonBU'', '''', ''Montedio Yamagata'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dMNh5kdn'', '''', ''Ehime FC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Q17PNMnc'', '''', ''Oita Trinita'');


/*  Poland 1st Liga  - 12492 - Qo6off6p   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ShUKWHDG'', '''', ''LKS Lodz'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pxXiDZkQ'', '''', ''Stal Mielec'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zBPYeTRl'', '''', ''Podbeskidzie Bielsko-Biala'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CrVUWAl8'', '''', ''Warta Poznan'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8h64p2iG'', '''', ''Wigry Suwalki'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YNkK4khO'', '''', ''Bruk-Bet Termalica Nieciecza'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dtqx13O8'', '''', ''MKS Puszcza'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jatrkvA8'', '''', ''Bytovia Bytow'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CCbwwqt7'', '''', ''Sandecja Nowy Sacz'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''rcipSgyk'', '''', ''Stomil Olsztyn'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pGdjhJ01'', '''', ''Chojniczanka Chojnice'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''C8Kg1k4R'', '''', ''Odra Opole'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MJijSTCe'', '''', ''GKS Jastrzebie'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vo6umLPj'', '''', ''Chrobry Glogow'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SQOrbYim'', '''', ''Rakow Czestochowa'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''K4AgRmS1'', '''', ''GKS Katowice'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''baXtU8YQ'', '''', ''GKS Tychy'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dzvozlRl'', '''', ''Garbarnia Krakow'');

/*  Iran Pro League  - 5579 - 2HzmcynI   */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8O8Bamai'', '''', ''Gostaresh'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6HP7tgt2'', '''', ''Zob Ahan'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''M5HFyp7p'', '''', ''Nassaji Mazandaran'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''bL7joAFo'', '''', ''Naft Ahvaz'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''nqFIkLT5'', '''', ''Sanat Naft'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KzfvmgGd'', '''', ''Persepolis'');

/*  EBPEFrRQ, AUSTRIA_BRISBEN */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SbgCQGdS'', '''', ''Brisbane K.'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8KHOzcvo'', '''', ''Bayside'');

/*  xbpjAGxq, EGYPT_PREMIER */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hAgPF9Zc'', '''', ''Arab Contractors'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2wpo7PBj'', '''', ''Enppi'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Q79lCRYM'', '''', ''El Ismaily'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''nqXQZgpI'', '''', ''Misr Elmaqasah'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EckpUnJ3'', '''', ''Haras El Hodood'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EPsYDm4A'', '''', ''Al Ahly'');

/*  W6BOzpK2, BUNDESLIGA */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''nVp0wiqd'', '''', ''Bayern Munich'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hQAtP9Sl'', '''', ''TSG Hoffenheim'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ne1oL3y7'', '''', ''Fortuna Dusseldorf'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fTVNku3I'', '''', ''Augsburg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fiEQZ7C7'', '''', ''SC Freiburg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8vndvXTk'', '''', ''Eintracht Frankfurt'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2y0u8Wrq'', '''', ''Hertha Berlin'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6FDqshzF'', '''', ''Nurnberg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Ig1f1fy3'', '''', ''Werder Bremen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dfNCCCzS'', '''', ''Hannover 96'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''nwkTahLL'', '''', ''VFL Wolfsburg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''0Ija0Ej9'', '''', ''Schalke 04'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''88HSzjDr'', '''', ''Borussia Monchengladbach'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''4jcj2zMd'', '''', ''Bayer Leverkusen'');

/*  jVMQJOHF, SWITZERLAND_CHALLENGE */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Ov2LFx62'', '''', ''Servette'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vRvKpKGc'', '''', ''Winterthur'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''zcUpovW3'', '''', ''Schaffhausen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Wd10iFbk'', '''', ''Lausanne Sports'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ULGuGvHA'', '''', ''Aarau'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''AHVOnJy3'', '''', ''Chiasso'');

/*  pv9Nf2KF, FRANCE_NATIONAL */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IL4RHuFr'', '''', ''Boulogne'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''4UGdHVMt'', '''', ''SO Cholet'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Ict2iv2P'', '''', ''Bourg en Bresse Peronnas 01'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''QsS5fv1S'', '''', ''Lyon Duchere'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fXSmZHX3'', '''', ''Drancy'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''E1wDrLsJ'', '''', ''Laval'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6NOhR4cm'', '''', ''Pau (n)'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tAAobNse'', '''', ''USL Dunkerque'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fPCzUHN1'', '''', ''Quevilly-Rouen Metropole'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2RZ8q1SC'', '''', ''Entente SSG'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''0pOdQOCg'', '''', ''Rodez Aveyron'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''OrDw2dg2'', '''', ''Marignane Gignac'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lrpZ4Lr7'', '''', ''Tours'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''rRGqeycC'', '''', ''FC Chambly'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''K6STnbAt'', '''', ''Villefranche'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''K01agKYi'', '''', ''US Avranches'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Uo57pG95'', '''', ''Concarneau'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ER0NeOOp'', '''', ''Le Mans'');

/*  vZiPmPJi, SPAIN_SEGUNDA */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''b7lODIzE'', '''', ''Extremadura UD'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Q51ZzMS6'', '''', ''Deportivo La Coruna'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''25tIqYiJ'', '''', ''Malaga'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''0ranWp9D'', '''', ''AD Alcorcon'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''I7HizxOs'', '''', ''Numancia'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hdWjLJUJ'', '''', ''Cadiz'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IDGLjl6p'', '''', ''Reus Deportiu'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''za7D2lO5'', '''', ''Real Zaragoza'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IyRQC2vM'', '''', ''Las Palmas'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UirAofN6'', '''', ''Albacete'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CWuejruc'', '''', ''Cordoba'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SzYzw34K'', '''', ''Real Oviedo'');

/*  EPQbW9EF, AUSTRIA_ERSTE */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''r9HwRaWH'', '''', ''Floridsdorfer AC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''655zEcZJ'', '''', ''Austria Lustenau'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''C4FBQHlQ'', '''', ''Young Violets Austria Wien'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''d2qFIbVn'', '''', ''SV Lafnitz'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jXu9HJ15'', '''', ''SV Horn'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6VKWwebP'', '''', ''SK Vorwarts Steyr'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Cv27lapN'', '''', ''FC Liefering'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SUpSZy5K'', '''', ''Kapfenberg SV'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fBe1n304'', '''', ''WSG Swarovski Wattens'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KIrFH87n'', '''', ''Blau Weiss Linz'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''htKjaUa7'', '''', ''Wacker Innsbruck Am'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''4bTx6ybm'', '''', ''SC Wiener Neustadt'');

/*  KIShoMk3, FRANCE_1 */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2akflumR'', '''', ''Lyon'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''nP6UzIU1'', '''', ''Strasbourg'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CjhkPw0k'', '''', ''Paris Saint Germain'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SAlF91iL'', '''', ''Angers'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lKkBAsxF'', '''', ''Amiens'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tItR6sEf'', '''', ''Reims'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Eyf00syR'', '''', ''Montpellier'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YL2QybFe'', '''', ''Saint Etienne'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''veuetnGG'', '''', ''Nantes'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''GjLn2QoH'', '''', ''Caen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YagoQJpq'', '''', ''Nice'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dIvQQaE7'', '''', ''Dijon'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MLmY2yB1'', '''', ''Toulouse'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pOtlc1qr'', '''', ''Nimes'');

/*  Opdcd08Q, TURKEY_SUPERLIGA */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EFRnJdkr'', '''', ''Caykur Rizespor'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''xQZ3CpVE'', '''', ''Buyuksehir Belediye Erzurumspor'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''OWyZjzgj'', '''', ''Ankaragucu'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MmsYDc03'', '''', ''Trabzonspor'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''0MJlDkrA'', '''', ''Goztepe AS'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''MsbmracL'', '''', ''Fenerbahce'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8pwUEwoc'', '''', ''Kayserispor'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''086C2Y6B'', '''', ''Yeni Malatyaspor'');


/*  6Nl8nagD, HOLLAND_1 */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IsK0b0aI'', '''', ''Almere City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6FRTNZ8p'', '''', ''Roda JC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''QRyYgO7J'', '''', ''Cambuur Leeuwarden'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lKIgIV5b'', '''', ''Jong AZ Alkmaar'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''4IzxgrNP'', '''', ''Den Bosch'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lvM1vra5'', '''', ''RKC Waalwijk'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YJaj0Opm'', '''', ''FC Eindhoven'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hG8POBb8'', '''', ''Go Ahead Eagles'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''SQGBcMU5'', '''', ''Helmond Sport'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dhOKTHGA'', '''', ''FC Twente Enschede'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''GncWwxTm'', '''', ''Jong Ajax'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fT0n14Vt'', '''', ''Dordrecht'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''40amSqFn'', '''', ''TOP Oss'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8Au8eRom'', '''', ''Jong PSV Eindhoven'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KK4FaFV3'', '''', ''Sparta Rotterdam'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6VbkuOqa'', '''', ''Volendam'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Aw0qTPat'', '''', ''Telstar'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YPQnAtpC'', '''', ''MVV Maastricht'');

/*  lpTTNvTq, FINLAND_VEIKKAUSLIIGA */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8GveH5dA'', '''', ''Vaasa VPS'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''C8bOhcyj'', '''', ''IFK Mariehamn'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WxHfCw7j'', '''', ''Honka Espoo'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pn1BFqRM'', '''', ''Lahti'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''pYGmWmwa'', '''', ''Ilves Tampere'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dM4FE3tT'', '''', ''TPS Turku'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''QwkNUoNH'', '''', ''Inter Turku'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CpkUGos4'', '''', ''RoPS Rovaniemi'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tSTln2zc'', '''', ''PS Kemi Kings'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hj3ima3I'', '''', ''Seinajoen JK'');

/*  dG2SqPrf, BELGIUM_A */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''Aw8l9bTk'', '''', ''KV Oostende'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''jPDfAdyT'', '''', ''Zulte Waregem'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''vsnvCI6G'', '''', ''Standard Liege'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''d2EjBxMM'', '''', ''Sint-Truidense'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''rVpPxw8H'', '''', ''Royal Antwerp'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''IXnm9vwh'', '''', ''Cercle Brugge'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''YmJAwcIR'', '''', ''Royal Excel Mouscron'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''roazgtic'', '''', ''KAS Eupen'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WIPDJ0hb'', '''', ''Sporting Charleroi'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''2o6njvyG'', '''', ''KV Kortrijk'');

/*  lfZXonNq, AUSTRALIA_NPL */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''EyU7XRbN'', '''', ''Kingston City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''bwmQTWpm'', '''', ''Heidelberg United'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''hp4oRUU5'', '''', ''Oakleigh Cannons'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dYCZxMVa'', '''', ''Pascoe Vale'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8UbVeMao'', '''', ''Avondale FC'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6ciKPSEO'', '''', ''South Melbourne'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''xEWWA2Ri'', '''', ''Port Melbourne Sharks'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''rmdM6WF4'', '''', ''Bentleigh Greens'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''juUyNy97'', '''', ''Dandenong Thunder'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''08OY5jVA'', '''', ''Northcote City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''t2xVSj0g'', '''', ''Hume City'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''KnlMUCVt'', '''', ''Green Gully Cavaliers'');


/*  nqMxclRN, CROATIA_1 */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''448T3rTI'', '''', ''Osijek'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''ENJqToLP'', '''', ''Slaven Koprivnica'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''WnmFp9Kg'', '''', ''HNK Gorica'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6JxGelZC'', '''', ''NK Rudes'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8G5ufQTg'', '''', ''D. Zagreb'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''CWwBJ6PA'', '''', ''Lok. Zagreb'');


/*  hleea1wH, CHECH_LIGA */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''fuXqHnxa'', '''', ''Bohemians 1905'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''6qA358jH'', '''', ''Sparta Praha'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''0EDHzr4L'', '''', ''SFC Opava'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''dKoDZLRL'', '''', ''MFK Karvina'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''lI6ddlih'', '''', ''Banik Ostrava'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''tKH71vSe'', '''', ''Dukla Praha'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''UL3SitR7'', '''', ''FK Pribram'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''4bp6yRjU'', '''', ''Slovan Liberec'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''r9XWmtLq'', '''', ''FK Teplice'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''viXGgnyB'', '''', ''Slavia Praha'');

/*  COuk57Ci, SERIE_A */
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''C06aJvIB'', '''', ''Juventus'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''URcSl02h'', '''', ''Lazio'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''69Dxbc61'', '''', ''Napoli'');
INSERT INTO PUBLIC.BOOKMAKER_TEAM(BOOKMAKER_TYPE, ITEM_FLASHSCORE_ID, BOOKMAKER_ID, NAME) VALUES(''SBOBET'', ''8Sa8HInO'', '''', ''AC Milan'');